const jsondata = [
  {
    name: "Meghs",
    cuisions:["Biriyani","North India","Chicken"],
    rating:"4.4",
    deliverytime:"20min",
    id:"1",
  },
  {
    name: "Panjurli",
    cuisions:["Chicken","Mutton","Veg"],
    rating:"3.4",
    deliverytime:"25min",
    id:"2",
  },
  {
    name: "KFC",
    cuisions:["Lolypop","Mutton","kurma"],
    rating:"4.1",
    deliverytime:"45min",
    id:"3",
  },
  {
    name: "KFC-2",
    cuisions:["Lolypop","Mutton","kurma"],
    rating:"4.6",
    deliverytime:"45min",
    id:"4",
  },
  {
    name: "Rocking",
    cuisions:["Cake","Juice"],
    rating:"3.4",
    deliverytime:"40min",
    id:"5",
  },
  {
    name: "Rocking",
    cuisions:["Cake","Juice"],
    rating:"3.4",
    deliverytime:"40min",
    id:"6",
  },
  {
    name: "Rocking",
    cuisions:["Cake","Juice"],
    rating:"3.4",
    deliverytime:"40min",
    id:"7",
  },
  {
    name: "Rocking",
    cuisions:["Cake","Juice"],
    rating:"3.4",
    deliverytime:"40min",
    id:"8",
  },
  {
    name: "Rocking",
    cuisions:["Cake","Juice"],
    rating:"3.4",
    deliverytime:"40min",
    id:"9",
  },
];
export default jsondata;
